### ISSUE TITLE
Using assert in the written tests

### ISSUE THREAD

**Issue by koladev32** [Transfa/sendhooks-engine#32]
**Description**:

The existing tests in the `sender` package are written using Go's native testing assertions. To improve readability, and maintainability, and provide clearer failure messages, we aim to incorporate the [`testify`](https://github.com/stretchr/testify) library.

**Tasks**:

1. **Incorporate `testify` into the project**:
   - Add `testify` to the project dependencies: `go get github.com/stretchr/testify/assert`.

2. **Refactor tests**:
   - Replace Go's built-in assertions (like `if err != nil`) with `testify`'s assertions (like `assert.NoError(t, err)`).
   - Utilize `testify`'s suite capabilities if there are shared setup and teardown procedures for test cases.

3. **Update error messages**:
   - With `testify`, error messages will be more descriptive by default. Custom error messages should be concise and clearly convey the failing condition.

4. **Run and verify tests**:
   - After refactoring, run all the tests to ensure they are still passing and that any failures provide clear messages.

5. **Update documentation**:
   - Add a note to the testing guidelines or README about using `testify` for future tests.

**Comment by Ishwarya-Selvaraj** [comment]
Hello @koladev32 I would like to work on this, also can you please add `Hactoberfest` label to this issue?

**Comment by koladev32** [comment]
> Hello @koladev32 I would like to work on this, also can you please add `Hactoberfest` label to this issue?

it is done. Feel free to work on this. If you need help, feel free to ask

**Comment by Ishwarya-Selvaraj** [comment]
Hello @koladev32 I have raised a pull request, can you please review and merge it?

**Comment by koladev32** [comment]
> Hello @koladev32 I have raised a pull request, can you please review and merge it?

Hello @Ishwarya-Selvaraj, good job. the review and the merge will be done in a few hours by @asiedu-kev

**Comment by Ishwarya-Selvaraj** [comment]
It is merged and we can close the issue!
