### ISSUE TITLE
Persisting data about the webhooks

### ISSUE THREAD

**Issue by koladev32** [Transfa/sendhooks-engine#42]
## Objective
Enhance the engine's usability by adding a UI to list hooks and view details about individual hooks, with data persistence in MongoDB.

## Requirements

- **MongoDB Configuration**
  - Configure MongoDB through environment variables for flexible deployment.

- **Database Initialization**
  - Automatically create a `hook` collection upon database connection if it doesn't exist.

- **Node.js Service**
  - Implement a Node.js service that listens to a Redis stream for hook creation, delivery updates, and failures.

- **API Endpoints**
  - `GET /sendhooks/hooks/`: List all hooks.
  - `GET /sendhooks/hooks/:hook_id/`: Retrieve details for a specific hook.

- **Hook Model**
  ```json
  {
    "id": "uuid",
    "status": "success|failed",
    "created": "datetime of creation",
    "delivered": "datetime of delivery",
    "error": "error text if applicable"
  }
- **Project Structure**
 - Place all Node.js service code within an `api` directory.
- **Dockerization**
 - Create a Dockerfile to run the project, naming the container sendhooks-engine-api.

**Comment by koladev32** [comment]
@gjivaros let me know what you think. This issue can be started even if it needs #45 to ensure it works well. I will work on the ticket. 

cc @asiedu-kev

**Comment by gjivaros** [comment]
Hello @koladev32 . I will assign this issue for myself. For the moment is OK for me. I don't know if the others have any  improvement

**Comment by asiedu-kev** [comment]
LGTM

**Comment by koladev32** [comment]
@gjivaros you can go on.

**Comment by gjivaros** [comment]
@koladev32 Can i setup with nestjs?!

**Comment by koladev32** [comment]
@gjivaros sorry, have not seen the comment. Why Nestjs? Is it not possible to go with just Express?

**Comment by koladev32** [comment]
@gjivaros you can start working on this. The #45 has been completed.

**Comment by gjivaros** [comment]
@koladev32 ok. I had already started with nestjs. I'm going to replace it with just express
