### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Ederene20** [Transfa/sendhooks-engine#82]
**Describe the bug**
Getting a runtime error when running `go run main.go` .

**To Reproduce**
1. Go to `sendhooks` directory
2. Execute `go run main.go`
3. See error

**Expected behavior**

I get the following error in the terminal :

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x67cc0c]

goroutine 1 [running]:
main.main()
	/sendhooks-engine/sendhooks/main.go:36 +0x2cc
exit status 2
```

**Screenshots**

![Screenshot from 2024-07-13 07 54 43](https://github.com/user-attachments/assets/f646fad7-a789-4a50-b6d2-b42919a53a8f)

**Desktop:**
 - OS: Ubuntu (Elementary OS 7.1 Horus)
 - Version: 22

**Comment by cedrick-ah** [comment]
I think that it is because the configuration are direclty parsed from the config.json file without any adaptation to match the configuration structure in code. This led to undefined variables in the configuration and therefore we have pointers that point to nothing. When trying to manipulate these null pointers we then get the so-called error. I will submit a PR to fix it.
The error is here:
```go
func LoadConfiguration(filename string) {
	once.Do(func() {
		file, err := os.Open(filename)
		if err != nil {
			log.Fatalf("Failed to open config file: %v", err)
		}
		defer file.Close()

		decoder := json.NewDecoder(file)
		err = decoder.Decode(&config) // config structure do not match config.json file structure
		fmt.Printf("&s", config.Broker)
		if err != nil {
			log.Fatalf("Failed to decode config file: %v", err)
		}
	})
}
```

**Comment by koladev32** [comment]
@cedrick-ah thanks for the diagnosis. I will check the PRs in few hours

**Comment by cedrick-ah** [comment]
Okay, I will be waiting for it.

**Comment by koladev32** [comment]
@Ederene20 please pull the project on the main branch to confirm the issue has been resolved.

**Comment by ederenee** [comment]
> @Ederene20 please pull the project on the main branch to confirm the issue has been resolved.

@koladev32 The issue has been resolved.  Thank you @cedrick-ah !!
